### ISSUE TITLE
CMake configuration is different when running from SSH vs in RDP session

### ISSUE THREAD

**Issue by pomeroy3** [microsoft/gr-azure#13]
Depending on the environment used to run cmake when building OOT modules in the Developer VM, python files may be installed in different directories. 

The build process should produce consistent results regardless of if a user is running CMAKE from a direct SSH terminal in the Developer VM or in a terminal inside a remote desktop session. 

[AB#10541](https://ag-ascii.visualstudio.com/a2b18d2f-d51c-4194-97e8-d6244d4a0156/_workitems/edit/10541)

**Comment by te20389911** [comment]
HI Team, Not able to install gr-azure OOT modules on Ubuntu. I tried all the Tag and brach. Getting error.after excute the cmake .. command.

**Comment by 777arc** [comment]
> HI Team, Not able to install gr-azure OOT modules on Ubuntu. I tried all the Tag and brach. Getting error.after excute the cmake .. command.

try deleting the /build directory and recreating it, then use `cmake -DCMAKE_FIND_ROOT_PATH=/usr ..`

**Comment by te20389911** [comment]
I already tried with cmake -DCMAKE_FIND_ROOT_PATH=/usr ..

But getting the same error.

The C compiler identification is GNU 9.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type not specified: defaulting to release.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
CMake Error at /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "Findspdlog.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "spdlog", but
  CMake did not find one.

  Could not find a package configuration file provided by "spdlog" with any
  of the following names:

    spdlogConfig.cmake
    spdlog-config.cmake

  Add the installation prefix of "spdlog" to CMAKE_PREFIX_PATH or set
  "spdlog_DIR" to a directory containing one of the above files.  If "spdlog"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /usr/local/lib/cmake/gnuradio/GnuradioConfig.cmake:13 (find_dependency)
  CMakeLists.txt:77 (find_package)


-- Configuring incomplete, errors occurred!
See also "/root/gr-azure/build/CMakeFiles/CMakeOutput.log".


Thanks!!
Tej



Internal - General Use

**Comment by 777arc** [comment]
@te20389911 `sudo apt install libspdlog-dev`  and whenever cmake complains it cant find something thats often the solution, install libxyz-dev

**Comment by te20389911** [comment]
HI Marc,

After Install libspdlog-dev then execute the cmake -DCMAKE_FIND_ROOT_PATH=/usr ..
After that I got the below error.

***@***.***:~/gr-azure/build# cmake -DCMAKE_FIND_ROOT_PATH=/usr ..
-- The CXX compiler identification is GNU 9.4.0
-- The C compiler identification is GNU 9.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type not specified: defaulting to release.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Checking for module 'gmp'
--   Found gmp, version 6.2.0
-- Found GMP: /usr/lib/x86_64-linux-gnu/libgmpxx.so
-- Using GMP.
-- Found MPLIB: /usr/lib/x86_64-linux-gnu/libgmpxx.so
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.71.0") found
components: date_time program_options system regex thread unit_test_framework
-- Found Volk: Volk::volk
-- User set python executable /usr/bin/python3
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.10")
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found suitable exact version "3.8.10")
CMake Error at /usr/local/lib/cmake/gnuradio/GnuradioConfig.cmake:40 (include):
  include could not find load file:

    /usr/local/lib/cmake/gnuradio/gnuradio-pmtConfig.cmake
Call Stack (most recent call first):
  CMakeLists.txt:77 (find_package)


CMake Error at /usr/local/lib/cmake/gnuradio/GnuradioConfig.cmake:41 (include):
  include could not find load file:

    /usr/local/lib/cmake/gnuradio/gnuradio-runtimeConfig.cmake
Call Stack (most recent call first):
  CMakeLists.txt:77 (find_package)


-- Found Git: /usr/bin/git
-- Extracting version information from git describe...
fatal: No annotated tags can describe '8ea50c8d4d3301e961354d824cef69537169a3f1'.
However, there were unannotated tags: try --tags.
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.17") found components: doxygen dot
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so
-- No C++ sources... skipping lib/
-- PYTHON and GRC components are enabled
-- No C++ sources... skipping python bindings
-- Configuring incomplete, errors occurred!
See also "/root/gr-azure/build/CMakeFiles/CMakeOutput.log".
See also "/root/gr-azure/build/CMakeFiles/CMakeError.log".


Thanks!!
Tej


Internal - General Use

**Comment by 777arc** [comment]
Do you have GNU Radio installed and working?

**Comment by te20389911** [comment]
HI Marc,


Yes, GNU Radio installed not getting any error during installation.
Is there any other way to check GNU Radio work properly or not?


Thanks!!
Tej



Internal - General Use

**Comment by 777arc** [comment]
You run `gnuradio-companion` then see if the window pops up, and if it does, you can try a starter flowgraph to make sure it can run https://wiki.gnuradio.org/index.php?title=Your_First_Flowgraph

**Comment by 777arc** [comment]
Also go ahead and open a new Issue if you run into further problems, since this Issue was unrelated

**Comment by te20389911** [comment]
Thanks !!marc

Installation done.. able to see GNU radio UI..



Internal - General Use
